"""initial schema

Revision ID: 031f265fd4c5
Revises: 
Create Date: 2026-04-29 14:35:47.661767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031f265fd4c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('jira_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_id', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_id')
    )
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_version_id', sa.Integer(), nullable=False),
    sa.Column('stat_total', sa.Integer(), nullable=False),
    sa.Column('stat_with_pr', sa.Integer(), nullable=False),
    sa.Column('stat_no_pr', sa.Integer(), nullable=False),
    sa.Column('stat_merged', sa.Integer(), nullable=False),
    sa.Column('stat_deployed_this', sa.Integer(), nullable=False),
    sa.Column('stat_deployed_prev', sa.Integer(), nullable=False),
    sa.Column('stat_unregistered_prs', sa.Integer(), nullable=False),
    sa.Column('unregistered_breakdown_needed', sa.Integer(), nullable=True),
    sa.Column('unregistered_breakdown_not_needed', sa.Integer(), nullable=True),
    sa.Column('unregistered_breakdown_no_ticket', sa.Integer(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jira_version_id'], ['jira_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_jira_version_id'), 'deployments', ['jira_version_id'], unique=False)
    op.create_table('release_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_version_id', sa.Integer(), nullable=False),
    sa.Column('confluence_page', sa.String(length=20), nullable=False),
    sa.Column('confluence_location', sa.String(length=500), nullable=False),
    sa.Column('confluence_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jira_version_id'], ['jira_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_notes_jira_version_id'), 'release_notes', ['jira_version_id'], unique=False)
    op.create_table('deployment_repos',
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('version_tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('deployment_id', 'repo_id')
    )
    op.create_index(op.f('ix_deployment_repos_repo_id'), 'deployment_repos', ['repo_id'], unique=False)
    op.create_table('deployment_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('jira_ticket_id', sa.Integer(), nullable=False),
    sa.Column('pr', sa.String(length=50), nullable=True),
    sa.Column('merged', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['jira_ticket_id'], ['jira_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_tickets_deployment_id'), 'deployment_tickets', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_tickets_jira_ticket_id'), 'deployment_tickets', ['jira_ticket_id'], unique=False)
    op.create_table('release_note_tickets',
    sa.Column('release_note_id', sa.Integer(), nullable=False),
    sa.Column('jira_ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jira_ticket_id'], ['jira_tickets.id'], ),
    sa.ForeignKeyConstraint(['release_note_id'], ['release_notes.id'], ),
    sa.PrimaryKeyConstraint('release_note_id', 'jira_ticket_id')
    )
    op.create_index(op.f('ix_release_note_tickets_jira_ticket_id'), 'release_note_tickets', ['jira_ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_note_tickets_jira_ticket_id'), table_name='release_note_tickets')
    op.drop_table('release_note_tickets')
    op.drop_index(op.f('ix_deployment_tickets_jira_ticket_id'), table_name='deployment_tickets')
    op.drop_index(op.f('ix_deployment_tickets_deployment_id'), table_name='deployment_tickets')
    op.drop_table('deployment_tickets')
    op.drop_index(op.f('ix_deployment_repos_repo_id'), table_name='deployment_repos')
    op.drop_table('deployment_repos')
    op.drop_index(op.f('ix_release_notes_jira_version_id'), table_name='release_notes')
    op.drop_table('release_notes')
    op.drop_index(op.f('ix_deployments_jira_version_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_table('repos')
    op.drop_table('jira_versions')
    op.drop_table('jira_tickets')
    # ### end Alembic commands ###
